### ISSUE TITLE
Cookie not set when it is provided along an HTTP 302 response

### ISSUE THREAD

**Issue by egefeyzioglu** [lamnhan066/http_session#1]
It doesn't seem like the library sets cookies correctly when being redirected.

I make a GET request to `raddle.me/login`, which results in an HTTP 302 redirect and cookies being set. The library does follow the redirect, but it doesn't seem to be setting the cookies properly.

My code:
```dart
static String raddleBase = "https://raddle.me";
static late HttpSession _httpSession;
//...
_httpSession = HttpSession.shared;
//...
final response = await _httpSession.get(Uri.parse("$raddleBase/login"));
```

Expected behaviour, using Chrome:
![image](https://github.com/vnniz/http_session/assets/12109705/04f0c450-20d8-4618-ba81-a152e544f0c0)
![image](https://github.com/vnniz/http_session/assets/12109705/0dcd851f-bcb8-40cf-8b87-ffaf4720c871)

mitmproxy snips for http_session:
![image](https://github.com/vnniz/http_session/assets/12109705/7786e546-86a0-48e7-9cb1-b251ff93e324)
![image](https://github.com/vnniz/http_session/assets/12109705/9ab254ed-c637-4f32-aecc-d8ff11147ab9)

**Comment by lamnhan066** [comment]
@egefeyzioglu I just released a `rc` version I rewrote the package to support adding the cookie to redirected URL. You can try it and let me know the result if possible. Thank you.

pub: https://pub.dev/packages/http_session/versions/0.2.0-rc.1
branch: https://github.com/vnniz/http_session/tree/support-redirected
