### ISSUE TITLE
Library ignores SSL errors

### ISSUE THREAD

**Issue by egefeyzioglu** [lamnhan066/http_session#2]
I just realised that this library ignores SSL errors, and it seems to be on purpose:

```dart
  /// Avoid badCertificate error
  IOClient _ioClient() {
    final HttpClient ioc = HttpClient();
    ioc.badCertificateCallback =
        (X509Certificate cert, String host, int port) => true;
    return IOClient(ioc);
  }
```

This should really either be documented _very_ clearly or removed since it makes any software using the library vulnerable to MitM attacks.

**Comment by lamnhan066** [comment]
Thank you for your report, I'll add a flag to control this feature and turn it off by default in the next release because it's a common issue when using HTTP to request. I also add a way to modify the `HttpClient` when creating a new `HttpSession`.

It will be something like this:

``` dart
  /// Create a new http session instance
  HttpSession({
    HttpClient? client,
    this.acceptBadCertificate = false,
    this.maxRedirects = 5,
    this.debugLog = false,
  }) {
    _httpDelegate = _ioClient(client);
  }

  /// Avoid badCertificate error
  IOClient _ioClient([HttpClient? client]) {
    final HttpClient ioc = client ?? HttpClient()
      ..badCertificateCallback =
          (X509Certificate cert, String host, int port) => acceptBadCertificate;

    return IOClient(ioc);
  }
```

**Comment by lamnhan066** [comment]
Hi @egefeyzioglu, a new [version](https://pub.dev/packages/http_session/versions/0.2.0-rc.2) that may resolve your issue is on the pub.dev. Please give me feedback if you try it.
