### ISSUE TITLE
Multiple cookies not handled

### ISSUE THREAD

**Issue by egefeyzioglu** [lamnhan066/http_session#4]
The library ignores multiple cookies sent to the client and only parses the first one. [RFC 2109](https://www.rfc-editor.org/rfc/rfc2109) allows for multiple `set-cookie` headers, as well as multiple comma-seperated cookies on a single header.

A stopgap solution would be something along the lines of:

```dart
  /// Update the cookie
  void _updateCookieHeaders(Map<String, String> headers) {
    final List<String>? rawCookies = headers[HttpHeaders.setCookieHeader]?.split(",");	
    for(String rawCookie in [...?rawCookies]){
		_print("rawCookie: $rawCookie");
        if (rawCookie != null) {
          final int index = rawCookie.indexOf(';');
          _headers[HttpHeaders.cookieHeader] =
               (_headers[HttpHeaders.cookieHeader] == "" ? "" : _headers[HttpHeaders.cookieHeader]) + 
               ((index == -1) ? rawCookie : rawCookie.substring(0, index));
        }
	}
  }
```

though ideally the `set-cookie` header would be properly parsed, it doesn't look like other parameters in the header are handled correctly either.

@vnniz I can work on this if you'd be okay with that, I'm asking first though because I don't want to write a parser then have it go to waste lol

**Comment by egefeyzioglu** [comment]
Also I can't tell if domains are segregated because if not that's a huge security issue

**Comment by lamnhan066** [comment]
@egefeyzioglu I'm not good at this area, I first create this package only to ignore the bad certificates issue and to save some important cookies. So if you're good at this area, I'm willing to merge your PRs.

**Comment by egefeyzioglu** [comment]
Sounds good!

**Comment by lamnhan066** [comment]
I'll close this comment because the conversation has ended
